[ DEBUG ][ 2022-05-27 08:18:49,493 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>
[ DEBUG ][ 2022-05-27 08:18:49,568 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>
[ DEBUG ][ 2022-05-27 08:18:49,570 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>
[ DEBUG ][ 2022-05-27 08:18:49,573 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>
[ DEBUG ][ 2022-05-27 08:18:49,575 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>
[ DEBUG ][ 2022-05-27 08:18:49,577 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>
[ DEBUG ][ 2022-05-27 08:18:49,581 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>
[ DEBUG ][ 2022-05-27 08:18:49,583 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>
[ DEBUG ][ 2022-05-27 11:44:11,404 ][ base ] ==> Exception while resolving variable 'branch_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [branch_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f5b95287ee0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5b95249700>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5b953e0c40>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet []>, 'voyage_total': 36, 'mission_total': 0, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f5b952038b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b952034f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203850>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203910>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203790>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203e50>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203ee0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203400>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203c40>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b95203f10>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b9532c0a0>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f5b9654b100>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953f0310>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b964fb8e0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95254c40>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b952546a0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953460a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95288160>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953fc520>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9538c070>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95288f40>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b952886d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9532aee0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b9525f550>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9525f2e0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 11:44:11,460 ][ base ] ==> Exception while resolving variable 'customer_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [customer_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f5b95287ee0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5b95249700>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5b953e0c40>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet []>, 'voyage_total': 36, 'mission_total': 0, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f5b952038b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b952034f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203850>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203910>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203790>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203e50>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203ee0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203400>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203c40>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b95203f10>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b9532c0a0>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f5b9654b100>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953f0310>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b964fb8e0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95254c40>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b952546a0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953460a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95288160>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953fc520>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9538c070>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95288f40>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b952886d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9532aee0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b9525f550>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9525f2e0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 11:44:11,466 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f5b95287ee0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5b95249700>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5b953e0c40>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet []>, 'voyage_total': 36, 'mission_total': 0, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f5b952038b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b952034f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203850>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203910>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203790>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203e50>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203ee0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203400>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b95203c40>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b95203f10>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b9532c0a0>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f5b9654b100>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953f0310>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b964fb8e0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95254c40>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b952546a0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953460a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95288160>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b953fc520>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9538c070>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95288f40>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b952886d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9532aee0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b9525f550>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b9525f2e0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 11:49:09,796 ][ base ] ==> Exception while resolving variable 'branch_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [branch_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f5b951e4f70>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5b94104580>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5b96578c70>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>]>, 'voyage_total': 36, 'mission_total': 1, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f5b941092b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109ac0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109d30>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109910>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109c40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109190>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109160>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b941095b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109a30>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b94109850>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b94109d00>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f5b9534d040>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96678400>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96580460>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd9a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdee0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b965809a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd430>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdb20>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96580f10>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd7c0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdc10>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96507520>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95368850>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b95368ca0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 11:49:09,809 ][ base ] ==> Exception while resolving variable 'customer_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [customer_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f5b951e4f70>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5b94104580>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5b96578c70>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>]>, 'voyage_total': 36, 'mission_total': 1, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f5b941092b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109ac0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109d30>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109910>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109c40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109190>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109160>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b941095b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109a30>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b94109850>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b94109d00>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f5b9534d040>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96678400>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96580460>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd9a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdee0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b965809a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd430>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdb20>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96580f10>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd7c0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdc10>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96507520>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95368850>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b95368ca0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 11:49:09,814 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f5b951e4f70>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5b94104580>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5b96578c70>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>]>, 'voyage_total': 36, 'mission_total': 1, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f5b941092b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109ac0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109d30>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109910>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109c40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109190>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109160>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b941095b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f5b94109a30>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b94109850>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f5b94109d00>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f5b9534d040>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96678400>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96580460>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd9a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdee0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b965809a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd430>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdb20>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96580f10>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b951fd7c0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b951fdc10>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b96507520>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f5b95368850>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f5b95368ca0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 13:32:23,877 ][ base ] ==> Exception while resolving variable 'branch_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [branch_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fa72131ae50>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa72267c1f0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa722631df0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>, <Mission: Client:  kankan>, <Mission: Client:  keita23>, <Mission: Client:  keita23>, <Mission: Client:  souley>]>, 'voyage_total': 36, 'mission_total': 5, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fa72130cbb0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130cd00>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130ce20>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130cf40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f30a0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f31c0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f32e0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f3400>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f3520>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212f3640>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212f3760>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fa7212fd9d0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214395e0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214396d0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa722676730>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa722674250>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa721439eb0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7226762b0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7226763d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72133fbe0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa722676580>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa722676eb0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72133f280>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa721498430>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214a6c40>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 13:32:23,897 ][ base ] ==> Exception while resolving variable 'customer_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [customer_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fa72131ae50>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa72267c1f0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa722631df0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>, <Mission: Client:  kankan>, <Mission: Client:  keita23>, <Mission: Client:  keita23>, <Mission: Client:  souley>]>, 'voyage_total': 36, 'mission_total': 5, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fa72130cbb0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130cd00>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130ce20>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130cf40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f30a0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f31c0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f32e0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f3400>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f3520>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212f3640>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212f3760>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fa7212fd9d0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214395e0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214396d0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa722676730>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa722674250>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa721439eb0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7226762b0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7226763d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72133fbe0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa722676580>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa722676eb0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72133f280>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa721498430>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214a6c40>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 13:32:23,912 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fa72131ae50>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa72267c1f0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa722631df0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>, <Mission: Client:  kankan>, <Mission: Client:  keita23>, <Mission: Client:  keita23>, <Mission: Client:  souley>]>, 'voyage_total': 36, 'mission_total': 5, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fa72130cbb0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130cd00>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130ce20>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa72130cf40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f30a0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f31c0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f32e0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f3400>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212f3520>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212f3640>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212f3760>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fa7212fd9d0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214395e0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214396d0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa722676730>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa722674250>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa721439eb0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7226762b0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7226763d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72133fbe0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa722676580>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa722676eb0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72133f280>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa721498430>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7214a6c40>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 13:32:35,048 ][ base ] ==> Exception while resolving variable 'branch_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'branch_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [branch_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fa7212c61f0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa722717460>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa72c376370>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>, <Mission: Client:  kankan>, <Mission: Client:  keita23>, <Mission: Client:  keita23>, <Mission: Client:  souley>]>, 'voyage_total': 36, 'mission_total': 5, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fa7212ce280>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce3d0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce4f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce610>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce730>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce850>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce970>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212cea90>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212cebb0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212cecd0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212cedf0>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fa7212df0d0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72130dcd0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72130dfa0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7226317f0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa721450700>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b0d00>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fc6a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fce20>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b5160>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fcb20>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fca00>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b5970>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fc0a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fcee0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 13:32:35,064 ][ base ] ==> Exception while resolving variable 'customer_count' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'customer_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [customer_count] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fa7212c61f0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa722717460>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa72c376370>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>, <Mission: Client:  kankan>, <Mission: Client:  keita23>, <Mission: Client:  keita23>, <Mission: Client:  souley>]>, 'voyage_total': 36, 'mission_total': 5, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fa7212ce280>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce3d0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce4f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce610>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce730>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce850>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce970>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212cea90>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212cebb0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212cecd0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212cedf0>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fa7212df0d0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72130dcd0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72130dfa0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7226317f0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa721450700>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b0d00>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fc6a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fce20>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b5160>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fcb20>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fca00>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b5970>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fc0a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fcee0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 13:32:35,077 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fa7212c61f0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa722717460>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa72c376370>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: lenoir>, <Voyage: kankan>, <Voyage: keita2>, <Voyage: keita23>, <Voyage: keita23>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: darkman>, <Voyage: souley>, <Voyage: keita2>, <Voyage: keita>, <Voyage: keita>, <Voyage: 1>, <Voyage: kankan>, <Voyage: 1>, <Voyage: keita2>, <Voyage: misterY>, '...(remaining elements truncated)...']>, 'mission': <QuerySet [<Mission: Client:  lenoir>, <Mission: Client:  kankan>, <Mission: Client:  keita23>, <Mission: Client:  keita23>, <Mission: Client:  souley>]>, 'voyage_total': 36, 'mission_total': 5, 'livreurs': [<User: jean>], 'voyage_en_cours': 4, 'voyage_valide': 1, 'voyage_echouee': 2}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fa7212ce280>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce3d0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce4f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce610>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce730>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce850>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212ce970>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212cea90>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fa7212cebb0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212cecd0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fa7212cedf0>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fa7212df0d0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-3 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72130dcd0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa72130dfa0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7226317f0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa721450700>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b0d00>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: branch_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fc6a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fce20>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b5160>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: customer_count>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fcb20>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fca00>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212b5970>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fa7212fc0a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fa7212fcee0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 15>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-05-27 14:02:15,601 ][ base ] ==> Exception while resolving variable 'id' in template 'website/front/frontspace.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'BoundWidget' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'BoundWidget' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [id] in <django.forms.boundfield.BoundWidget object at 0x7f0a69b4d790>
[ DEBUG ][ 2022-05-27 14:02:17,261 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>
[ DEBUG ][ 2022-05-27 14:02:17,265 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>
[ DEBUG ][ 2022-05-27 14:02:17,266 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>
[ DEBUG ][ 2022-05-27 14:02:17,269 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>
[ DEBUG ][ 2022-05-27 14:02:17,275 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>
[ DEBUG ][ 2022-05-27 14:02:17,278 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>
[ DEBUG ][ 2022-05-27 14:02:17,283 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>
[ DEBUG ][ 2022-05-27 14:02:17,286 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'api.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/api/urls/base.py'> (None:None) 'api/v1/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'website/front/js/main.js'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>
